development:
  MERCHANT_ID = "158670000"
  USER_NAME = paymentprocessor
  PASSWORD = GOL2YDgb7exMjD
  PASSCODE = A5B59392C6304f7288b2d7793742a6a6
  
test:
  MERCHANT_ID = "158670000"
  USER_NAME = paymentprocessor
  PASSWORD = GOL2YDgb7exMjD
  PASSCODE = A5B59392C6304f7288b2d7793742a6a6

production:
  MERCHANT_ID = "158670000"
  USER_NAME = paymentprocessor
  PASSWORD = GOL2YDgb7exMjD
  PASSCODE = A5B59392C6304f7288b2d7793742a6a6