development:
  MERCHANT_ID: tvzpwtsvjxsy24z4
  PUBLIC_KEY: bwzwjyhtx9t3mpgy
  PRIVATE_KEY: a6f29d0afe51edc27102a042a82258e3
  
test:
  MERCHANT_ID: tvzpwtsvjxsy24z4
  PUBLIC_KEY: bwzwjyhtx9t3mpgy
  PRIVATE_KEY: a6f29d0afe51edc27102a042a82258e3
  
production:
  MERCHANT_ID: tvzpwtsvjxsy24z4
  PUBLIC_KEY: bwzwjyhtx9t3mpgy
  PRIVATE_KEY: a6f29d0afe51edc27102a042a82258e3