development:
  # redirect url
  REDIRECT_URL: https://www.sandbox.paypal.com/webscr?cmd=_ap-payment&paykey=
    
  # specify the 3-token values.    
  USER: middle_1312472948_biz_api1.gmail.com
  PASSWORD:  "1312472987"
  SIGNATURE: AQeoLK6k17n.8dndObjia1jsnKl4AhKjCtA3eFn0dIca9CKsL-R6vB7x 
          
  #    @@endpoints 
  API_SERVER:  svcs.sandbox.paypal.com

  # Proxy information of the client environment.   @@proxy_info 
  USE_PROXY:  false
  PROXY_ADDRESS: nil
  PROXY_PORT: nil
  PROXY_USER: nil
  PROXY_PASSWORD: nil 

  # Information needed for tracking purposes.   @@client_details
  IP_ADDRESS: 127.0.0.1
  APPLICATION_ID: APP-80W284485P519543T
  DEVICE_ID: mydevice  
  
  # Information needed for tracking purposes.   @@client_info   
  VERSION: "4.0"
  SOURCE: PayPalRubySDKV1.2.0


test:
  # redirect url
  REDIRECT_URL: https://www.sandbox.paypal.com/webscr?cmd=_ap-payment&paykey=
  
  # specify the 3-token values.    
  USER: middle_1312472948_biz_api1.gmail.com
  PASSWORD:  "1312472987"
  SIGNATURE: AQeoLK6k17n.8dndObjia1jsnKl4AhKjCtA3eFn0dIca9CKsL-R6vB7x
          
  #    @@endpoints 
  API_SERVER:  svcs.sandbox.paypal.com

  # Proxy information of the client environment.   @@proxy_info 
  USE_PROXY:  false
  PROXY_ADDRESS: nil
  PROXY_PORT: nil
  PROXY_USER: nil
  PROXY_PASSWORD: nil 

  # Information needed for tracking purposes.   @@client_details
  IP_ADDRESS: 127.0.0.1
  APPLICATION_ID: APP-80W284485P519543T
  DEVICE_ID: mydevice 

  # Information needed for tracking purposes.   @@client_info   
  VERSION: "4.0"
  SOURCE: PayPalRubySDKV1.2.0 

 
production:
  # redirect url
  #REDIRECT_URL: https://www.paypal.com/webscr?cmd=_ap-payment&paykey=
  REDIRECT_URL: https://www.sandbox.paypal.com/webscr?cmd=_ap-payment&paykey=

  # specify the 3-token values.    
  #USER: paul.chan_api1.justformyfriends.com
  #PASSWORD:  6CLFZ8ESCJUMK6XF
  #SIGNATURE: A2eXLsICE-Kw6UV4hYLnHldjmkqeAW15c76rWMuiBLf9JlSC85XCYR9z
  USER: middle_1312472948_biz_api1.gmail.com
  PASSWORD:  "1312472987"
  SIGNATURE: AQeoLK6k17n.8dndObjia1jsnKl4AhKjCtA3eFn0dIca9CKsL-R6vB7x
          
  #    @@endpoints 
  #API_SERVER:  svcs.paypal.com
  API_SERVER:  svcs.sandbox.paypal.com

  # Proxy information of the client environment.   @@proxy_info 
  USE_PROXY:  false
  PROXY_ADDRESS: nil
  PROXY_PORT: nil
  PROXY_USER: nil
  PROXY_PASSWORD: nil 

  # Information needed for tracking purposes.   @@client_details
  IP_ADDRESS: 127.0.0.1
  APPLICATION_ID: APP-80W284485P519543T
  DEVICE_ID: mydevice 

  # Information needed for tracking purposes.   @@client_info   
  VERSION: "4.0"
  SOURCE: PayPalRubySDKV1.2.0  