development:
  COMMISSION: 2.9
  PAYPAL_ACCOUNT: middle_1312472948_biz@gmail.com
  FEES_PAYER: EACHRECEIVER
  FILE_HOST: files.getkickbak.com
  PHOTO_HOST : photos.getkickbak.com
  AMAZON_FILES_BUCKET: files.getkickbak.com
  AMAZON_PHOTOS_BUCKET: photos.getkickbak.com
  REDIS_URL: "redis://kickbak:028ab069d968aa7768089e0f7f02c8ac@drum.redistogo.com:9431/"  
  DEBUG_MODE: true
  
test:  
  COMMISSION: 2.9
  PAYPAL_ACCOUNT: middle_1312472948_biz@gmail.com
  FEES_PAYER: EACHRECEIVER
  FILE_HOST: files.getkickbak.com
  PHOTO_HOST : photos.getkickbak.com
  AMAZON_FILES_BUCKET: files.getkickbak.com
  AMAZON_PHOTOS_BUCKET: photos.getkickbak.com
  REDIS_URL: "redis://kickbak:028ab069d968aa7768089e0f7f02c8ac@drum.redistogo.com:9431/"  
  DEBUG_MODE: false
  
production:
  COMMISSION: 2.9
  PAYPAL_ACCOUNT: payment@justformyfriends.com
  FEES_PAYER: EACHRECEIVER
  FILE_HOST: files.getkickbak.com
  PHOTO_HOST : photos.getkickbak.com
  AMAZON_FILES_BUCKET: files.getkickbak.com
  AMAZON_PHOTOS_BUCKET: photos.getkickbak.com
  #REDIS_URL: "redis://username:password@127.0.0.1:6379/"
  REDIS_URL: "redis://kickbak:4581c2433f1c544dbac343b89388d88e@gar.redistogo.com:9108"
  DEBUG_MODE: false