development:
  COMMISSION: 2.9
  PAYPAL_ACCOUNT: middle_1312472948_biz@gmail.com
  FEES_PAYER: EACHRECEIVER
  FILE_HOST: files.justformyfriends.com
  PHOTO_HOST : photos.justformyfriends.com
  AMAZON_FILES_BUCKET: files.justformyfriends.com
  AMAZON_PHOTOS_BUCKET: photos.justformyfriends.com
  
test:  
  COMMISSION: 2.9
  PAYPAL_ACCOUNT: middle_1312472948_biz@gmail.com
  FEES_PAYER: EACHRECEIVER
  FILE_HOST: files.justformyfriends.com
  PHOTO_HOST : photos.justformyfriends.com
  AMAZON_FILES_BUCKET: files.justformyfriends.com
  AMAZON_PHOTOS_BUCKET: photos.justformyfriends.com
  
production:
  COMMISSION: 2.9
  PAYPAL_ACCOUNT: middle_1312472948_biz@gmail.com
  FEES_PAYER: EACHRECEIVER
  FILE_HOST: files.justformyfriends.com
  PHOTO_HOST : photos.justformyfriends.com
  AMAZON_FILES_BUCKET: files.justformyfriends.com
  AMAZON_PHOTOS_BUCKET: photos.justformyfriends.com