development:
  #FILE_HOST: s3.amazonaws.com/devfiles.getkickbak.com
  #PHOTO_HOST : s3.amazonaws.com/devphotos.getkickbak.com
  FILE_HOST: devfiles.getkickbak.com
  PHOTO_HOST : devphotos.getkickbak.com
  AMAZON_FILES_BUCKET: devfiles.getkickbak.com
  AMAZON_PHOTOS_BUCKET: devphotos.getkickbak.com
  REDIS_URL: "redis://kickbak:028ab069d968aa7768089e0f7f02c8ac@drum.redistogo.com:9431/"  
  PUSHWOOSH_APP_CODE: 93D8A-5BE72
  PUSHWOOSH_APP_TOKEN: stxBkSy2dhaTSgfgPOt9ZvN/D8Sa9ig95jfMl5H0RUTRh9X9PUsU0ZYcsdIHLzn7rknASD/ohiYgU72xRwP1
  PUSHWOOSH_LOGIN: web2dot0
  PUSHWOOSH_PASSWORD: Risc6000
  SIMULATOR_MODE: false
  GENERATE_QRCODE: false
  FACEBOOK_APP_NAMESPACE: devgetkickbak
  FACEBOOK_APP_ID: "477780595628080"
  FACEBOOK_APP_SECRET: "f47bc95247d475ca734b3a72e0bb544c"
  PLIVO_AUTH_ID: "MAOWZHNGZKYJA3NDKXMW"
  PLIVO_AUTH_TOKEN: "NmQ0ZjMzZDk4OGMxZjNlZWI4YTY0ZmE1NzVhMjJl"
  PLIVO_NUMBER: "12892751595"
  TWILIO_ACCOUNT_ID: "AC34b522c83a73bc2fc2251068495c7db9"
  TWILIO_AUTH_TOKEN: "8f349236bd1d2c4ccd0274a58cef05ec"
  TWILIO_NUMBER: "+16479316204"
test:
  #FILE_HOST: s3.amazonaws.com/devfiles.getkickbak.com
  #PHOTO_HOST : s3.amazonaws.com/devphotos.getkickbak.com
  FILE_HOST: devfiles.getkickbak.com
  PHOTO_HOST : devphotos.getkickbak.com
  AMAZON_FILES_BUCKET: devfiles.getkickbak.com
  AMAZON_PHOTOS_BUCKET: devphotos.getkickbak.com
  REDIS_URL: "redis://kickbak:028ab069d968aa7768089e0f7f02c8ac@drum.redistogo.com:9431/"  
  PUSHWOOSH_APP_CODE: 93D8A-5BE72
  PUSHWOOSH_APP_TOKEN: stxBkSy2dhaTSgfgPOt9ZvN/D8Sa9ig95jfMl5H0RUTRh9X9PUsU0ZYcsdIHLzn7rknASD/ohiYgU72xRwP1
  PUSHWOOSH_LOGIN: web2dot0
  PUSHWOOSH_PASSWORD: Risc6000
  SIMULATOR_MODE: true
  GENERATE_QRCODE: false
  FACEBOOK_APP_NAMESPACE: devgetkickbak
  FACEBOOK_APP_ID: "477780595628080"
  FACEBOOK_APP_SECRET: "f47bc95247d475ca734b3a72e0bb544c"
  PLIVO_AUTH_ID: "MAOWZHNGZKYJA3NDKXMW"
  PLIVO_AUTH_TOKEN: "NmQ0ZjMzZDk4OGMxZjNlZWI4YTY0ZmE1NzVhMjJl"
  PLIVO_NUMBER: "12892751595"
  TWILIO_ACCOUNT_ID: "AC34b522c83a73bc2fc2251068495c7db9"
  TWILIO_AUTH_TOKEN: "8f349236bd1d2c4ccd0274a58cef05ec"
  TWILIO_NUMBER: "+16479316204"
production:
  #FILE_HOST: s3.amazonaws.com/files.getkickbak.com
  #PHOTO_HOST : s3.amazonaws.com/photos.getkickbak.com
  FILE_HOST: files.getkickbak.com
  PHOTO_HOST : photos.getkickbak.com
  AMAZON_FILES_BUCKET: files.getkickbak.com
  AMAZON_PHOTOS_BUCKET: photos.getkickbak.com
  #REDIS_URL: "redis://username:password@127.0.0.1:6379/"
  REDIS_URL: "redis://kickbak:4581c2433f1c544dbac343b89388d88e@gar.redistogo.com:9108"
  PUSHWOOSH_APP_CODE: 4fef6fb0691c12.54726991
  PUSHWOOSH_APP_TOKEN: stxBkSy2dhaTSgfgPOt9ZvN/D8Sa9ig95jfMl5H0RUTRh9X9PUsU0ZYcsdIHLzn7rknASD/ohiYgU72xRwP1
  #PUSHWOOSH_APP_CODE: 4fef50b25b2f16.74735670
  PUSHWOOSH_LOGIN: web2dot0
  PUSHWOOSH_PASSWORD: Risc6000
  SIMULATOR_MODE: false
  GENERATE_QRCODE: true
  FACEBOOK_APP_NAMESPACE: getkickbak
  FACEBOOK_APP_ID: "197968780267830"
  FACEBOOK_APP_SECRET: "080cb42570fde6ced464aa083e7b1c5a"
  PLIVO_AUTH_ID: "MAOWZHNGZKYJA3NDKXMW"
  PLIVO_AUTH_TOKEN: "NmQ0ZjMzZDk4OGMxZjNlZWI4YTY0ZmE1NzVhMjJl"
  PLIVO_NUMBER: "12892751595"
  TWILIO_ACCOUNT_ID: "AC34b522c83a73bc2fc2251068495c7db9"
  TWILIO_AUTH_TOKEN: "8f349236bd1d2c4ccd0274a58cef05ec"
  TWILIO_NUMBER: "+16479316204"