development:
  COMMISSION: 2.9
  PAYPAL_ACCOUNT: middle_1312472948_biz@gmail.com
  FEES_PAYER: EACHRECEIVER
  FILE_HOST: files.justformyfriends.com
  PHOTO_HOST : photos.justformyfriends.com
  AMAZON_FILES_BUCKET: files.justformyfriends.com
  AMAZON_PHOTOS_BUCKET: photos.justformyfriends.com
  REDIS_URL: "redis://justformyfriends:5506b4d6a5868ccdfbf6c36531214b1a@stingfish.redistogo.com:9112/"  
  
test:  
  COMMISSION: 2.9
  PAYPAL_ACCOUNT: middle_1312472948_biz@gmail.com
  FEES_PAYER: EACHRECEIVER
  FILE_HOST: files.justformyfriends.com
  PHOTO_HOST : photos.justformyfriends.com
  AMAZON_FILES_BUCKET: files.justformyfriends.com
  AMAZON_PHOTOS_BUCKET: photos.justformyfriends.com
  REDIS_URL: "redis://justformyfriends:5506b4d6a5868ccdfbf6c36531214b1a@stingfish.redistogo.com:9112/"  
  
production:
  COMMISSION: 2.9
  PAYPAL_ACCOUNT: payment@justformyfriends.com
  FEES_PAYER: EACHRECEIVER
  FILE_HOST: files.justformyfriends.com
  PHOTO_HOST : photos.justformyfriends.com
  AMAZON_FILES_BUCKET: files.justformyfriends.com
  AMAZON_PHOTOS_BUCKET: photos.justformyfriends.com
  REDIS_URL: "redis://username:password@127.0.0.1:6379/"
