#merchant_summary:
#  cron: 0 0 * * Mon
#  class: MerchantSummary
#  description: Merchant Summary
birthday_reminders:
  cron: 0 1 * * *
  class: BirthdayReminders
  description: Merchant Triggers
merchant_payments:
  cron: 0 0 1 * *
  class: MerchantPayments
  description: Merchant Payments
#merchant_triggers:
#  cron: 0 2 * * *
#  class: MerchantTriggers
#  description: Merchant Triggers
registration_reminders:
  cron: 0 8 * * *
  class: RegistrationReminders
  description: Registration Reminders  
account_balance_summaries:
  cron: 0 0 1-7,15-21 * 3
  class: AccountBalanceSummaries
  description: Account Balance Summaries