#merchant_summary:
#  cron: 0 0 * * Mon
#  class: MerchantSummary
#  description: Merchant Summary
merchant_payments:
  cron: 0 0 1 * *
  class: MerchantPayments
  description: Merchant Payments
registration_reminders:
  cron: 0 8 * * *
  class: RegistrationReminders
  description: Registration Reminders