merchant_summary_newsletters:
  cron: 0 0 * * Mon
  class: MerchantSummaryNewsletters
  description: Merchant Summary Newsletters
merchant_payments:
  cron: 0 0 1 * *
  class: MerchantPayments
  description: Merchant Payments  
expire_user_points:
  cron: 0 0 1 * *
  class: ExpireUserPoints
  description: Expire User Points
points_expiration_reminders:  
  cron: 0 0 1 * *
  class: PointsExpirationReminders
  description: Points Expiration Reminders
prize_expiration_reminders:
  cron: 0 1 * * *
  class: PrizeExpirationReminders
  description: Prize Expiration Reminders
voucher_expiration_reminders:
  cron: 0 1 * * *
  class: VoucherReminders
  description: Voucher Reminders
voucher_payments:
  cron: 0 0 * * Mon
  class: VoucherPayments
  args: true
  description: Voucher Payments  
voucher_payments_capture:
  cron: 0 * * * *
  class: VoucherPaymentsCapture
  description: Voucher Payments Capture