voucher_reminders:
  cron: 0 1 * * *
  class: VoucherReminders
  description: Voucher Reminders
voucher_payments:
  cron: 0 0 * * Mon
  class: VoucherPayments
  args: true
  description: Voucher Payments  