merchant_summary_newsletters:
  cron: 0 0 * * Mon
  class: MerchantSummaryNewsletters
  description: Merchant Summary Newsletters
expire_user_points:
  cron: 0 0 1 * *
  class: ExpireUserPoints
  description: Expire User Points  
voucher_reminders:
  cron: 0 1 * * *
  class: VoucherReminders
  description: Voucher Reminders
voucher_payments:
  cron: 0 0 * * Mon
  class: VoucherPayments
  args: true
  description: Voucher Payments  
voucher_payments_capture:
  cron: 0 * * * *
  class: VoucherPaymentsCapture
  description: Voucher Payments Capture