merchant_summary:
  cron: 0 0 * * Mon
  class: MerchantSummary
  description: Merchant Summary
merchant_payment_plans:
  cron: 0 0 1 * *
  class: MerchantPaymentPlans
  description: Merchant Payment Plans
registration_reminders:
  cron: 0 8 * * *
  class: RegistrationReminders
  description: Registration Reminders