INSERT INTO customer_segments VALUES (1, 'all');
INSERT INTO customer_segments VALUES (2, 'custom');
INSERT INTO customer_segments VALUES (3, 'newly_joined');
INSERT INTO customer_segments VALUES (4, 'very_frequent_last_1_month');
INSERT INTO customer_segments VALUES (5, 'very_frequent_last_3_month');
INSERT INTO customer_segments VALUES (6, 'very_frequent_last_6_month');
INSERT INTO customer_segments VALUES (7, 'somewhat_frequent_last_1_month');
INSERT INTO customer_segments VALUES (8, 'somewhat_frequent_last_3_month');
INSERT INTO customer_segments VALUES (9, 'somewhat_frequent_last_6_month');
INSERT INTO customer_segments VALUES (10, 'not_frequent_last_1_month');
INSERT INTO customer_segments VALUES (11, 'not_frequent_last_3_month');
INSERT INTO customer_segments VALUES (12, 'not_frequent_last_6_month');
INSERT INTO customer_segments VALUES (13, 'top_5_percent');
INSERT INTO customer_segments VALUES (14, 'top_10_percent');
INSERT INTO customer_segments VALUES (15, 'top_15_percent');
INSERT INTO customer_segments VALUES (16, 'top_20_percent');
INSERT INTO customer_segments VALUES (17, 'top_25_percent');
INSERT INTO customer_segments VALUES (18, 'last_visited_10_days');
INSERT INTO customer_segments VALUES (19, 'last_visited_20_days');
INSERT INTO customer_segments VALUES (20, 'last_visited_30_days');
INSERT INTO customer_segments VALUES (21, 'last_visited_60_days');
INSERT INTO customer_segments VALUES (22, 'last_visited_90_days');
INSERT INTO customer_segments VALUES (22, 'last_visited_180_days');

INSERT INTO customer_segment_visit_ranges VALUES (1, 'very_frequent_last_1_month', 1, 2, 0);
INSERT INTO customer_segment_visit_ranges VALUES (1, 'very_frequent_last_3_month', 3, 4, 0);
INSERT INTO customer_segment_visit_ranges VALUES (1, 'very_frequent_last_6_month', 6, 9, 0);
INSERT INTO customer_segment_visit_ranges VALUES (2, 'very_frequent_last_1_month', 1, 3, 0);
INSERT INTO customer_segment_visit_ranges VALUES (2, 'very_frequent_last_3_month', 3, 9, 0);
INSERT INTO customer_segment_visit_ranges VALUES (2, 'very_frequent_last_6_month', 6, 18, 0);
INSERT INTO customer_segment_visit_ranges VALUES (3, 'very_frequent_last_1_month', 1, 6, 0);
INSERT INTO customer_segment_visit_ranges VALUES (3, 'very_frequent_last_3_month', 3, 18, 0);
INSERT INTO customer_segment_visit_ranges VALUES (3, 'very_frequent_last_6_month', 6, 36, 0);
INSERT INTO customer_segment_visit_ranges VALUES (4, 'very_frequent_last_1_month', 1, 12, 0);
INSERT INTO customer_segment_visit_ranges VALUES (4, 'very_frequent_last_3_month', 3, 36, 0);
INSERT INTO customer_segment_visit_ranges VALUES (4, 'very_frequent_last_6_month', 6, 72, 0);
INSERT INTO customer_segment_visit_ranges VALUES (1, 'somewhat_frequent_last_1_month', 1, 1, 2);
INSERT INTO customer_segment_visit_ranges VALUES (1, 'somewhat_frequent_last_3_month', 3, 2, 4);
INSERT INTO customer_segment_visit_ranges VALUES (1, 'somewhat_frequent_last_6_month', 6, 4, 9);
INSERT INTO customer_segment_visit_ranges VALUES (2, 'somewhat_frequent_last_1_month', 1, 1, 3);
INSERT INTO customer_segment_visit_ranges VALUES (2, 'somewhat_frequent_last_3_month', 3, 4, 9);
INSERT INTO customer_segment_visit_ranges VALUES (2, 'somewhat_frequent_last_6_month', 6, 9, 18);
INSERT INTO customer_segment_visit_ranges VALUES (3, 'somewhat_frequent_last_1_month', 1, 3, 6);
INSERT INTO customer_segment_visit_ranges VALUES (3, 'somewhat_frequent_last_3_month', 3, 9, 18);
INSERT INTO customer_segment_visit_ranges VALUES (3, 'somewhat_frequent_last_6_month', 6, 18, 36);
INSERT INTO customer_segment_visit_ranges VALUES (4, 'somewhat_frequent_last_1_month', 1, 6, 12);
INSERT INTO customer_segment_visit_ranges VALUES (4, 'somewhat_frequent_last_3_month', 3, 18, 36);
INSERT INTO customer_segment_visit_ranges VALUES (4, 'somewhat_frequent_last_6_month', 6, 36, 72);
INSERT INTO customer_segment_visit_ranges VALUES (1, 'not_frequent_last_1_month', 1, 0, 1);
INSERT INTO customer_segment_visit_ranges VALUES (1, 'not_frequent_last_3_month', 3, 1, 2);
INSERT INTO customer_segment_visit_ranges VALUES (1, 'not_frequent_last_6_month', 6, 2, 4);
INSERT INTO customer_segment_visit_ranges VALUES (2, 'not_frequent_last_1_month', 1, 0, 1);
INSERT INTO customer_segment_visit_ranges VALUES (2, 'not_frequent_last_3_month', 3, 2, 4);
INSERT INTO customer_segment_visit_ranges VALUES (2, 'not_frequent_last_6_month', 6, 4, 9);
INSERT INTO customer_segment_visit_ranges VALUES (3, 'not_frequent_last_1_month', 1, 1, 3);
INSERT INTO customer_segment_visit_ranges VALUES (3, 'not_frequent_last_3_month', 3, 4, 9);
INSERT INTO customer_segment_visit_ranges VALUES (3, 'not_frequent_last_6_month', 6, 9, 18);
INSERT INTO customer_segment_visit_ranges VALUES (4, 'not_frequent_last_1_month', 1, 3, 6);
INSERT INTO customer_segment_visit_ranges VALUES (4, 'not_frequent_last_3_month', 3, 9, 18);
INSERT INTO customer_segment_visit_ranges VALUES (4, 'not_frequent_last_6_month', 6, 18, 36);